### ISSUE TITLE
Error executing 02_molecular_setup tutorial

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#1]
Running interactively [02_molecular_setup.ipynb](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/01_introduction/02_molecular_setup.ipynb ) on Ubuntu Linux with BSS 2023.2.2 , python 3.9.16 triggers a runtime error

![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/fd7c3e94-58a6-466f-9656-c18db04dd354)

**Comment by lohedges** [comment]
This is because of the new Sire search functionality. We'll need to call `.molecules()` on the search result to convert it to a molecule object, e.g.:

```python
for ion in search.molecules():
...
```

(Or do it directly when searching.)

**Comment by jmichel80** [comment]
Fixed by https://github.com/OpenBioSim/BioSimSpaceTutorials/pull/14
