### ISSUE TITLE
Remove doc for freenergy workflows in tutorial 4: 02_analysis_rbfe.ipynb

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#10]
Section 2 of [this notebook ](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/04_fep/02_RBFE/02_analysis_rbfe.ipynb)could be removed as it requires the deprecated package free energy workflows that we may not wish to support moving on.

Pinging @annamherz for approval.

**Comment by jmichel80** [comment]
We may also wish to use a less noisy dataset of RBFEs to generate decent looking scatter plots.

**Comment by jmichel80** [comment]
@annamherz - could you look at providing a more precise dataset ? 
@mb2055 - it's ok to go ahead and remove freenergyworkflows

**Comment by jmichel80** [comment]
the plan is to keep cinnabar in the tutorial.

**Comment by jmichel80** [comment]
partially addressed with #24 
will close when @annamherz has updated the notebook with new edges data

**Comment by annamherz** [comment]
> will close when @annamherz has updated the notebook with new edges data

added!
