### ISSUE TITLE
Tutorial 4: 02_analysis_abfe

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#12]
This [notebook](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/04_fep/03_ABFE/02_analysis_abfe.ipynb) will not currently work with BSS releases. We will have to migrate functionality in the sandpit, and optionally migrate the sandpit into the main codebase.

**Comment by fjclark** [comment]
@jmichel80 I can confirm that my code in [this PR](https://github.com/OpenBioSim/biosimspace/pull/104) allows both ABFE notebooks to run without issues once I have:

1) Unzipped the output files (I will push the unzipped output soon - there is only a minor increase in size).
2) Updated the plotting functionality to use the code in [this PR](https://github.com/OpenBioSim/biosimspace/pull/107).

The final remaining issue is that **the free energy changes using the Exscientia sandpit analysis are completely insane**. Using the Exscientia sandpit code (which uses alchemlyb), I get 1.0 kcal / mol for the bound discharge leg, while I get the expected -11.4 kcal / mol using the main version (native SOMD analysis). I'll see if I can find the issue with the alchemlyb analysis when I'm back from leave.
