### ISSUE TITLE
Squash repo on first release

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/BioSimSpaceTutorials#20]
This repository still takes a long time to clone. When we are ready for submission (or have a fully working set of initial tutorials) I wonder whether it would be best to create a fresh repository with the final files. This would remove history, but would remove old binary blobs for input/analysis files which have been removed. If we were worried about history, then we could merge back to `michellab` before creating the new repo. We might also consider renaming the repo to `biosimspace_tutorials` for consistency with the other OpenBioSIm repositories.

**Comment by jmichel80** [comment]
i don't think we need to keep the repo history in michellab.

**Comment by lohedges** [comment]
No problem. I can do this once we're happy with everything.

**Comment by lohedges** [comment]
This isn't completed. I've not done anything yet. Will do when all the material is finalised.

**Comment by lohedges** [comment]
You were obviously having too much fun closing issues.

**Comment by jmichel80** [comment]
Yes clearly overzealous

**Comment by jmichel80** [comment]
I think we have everything in place now to squash the repository. I can repackage the missing trajectory file from Adele's tutorial at a later point. 
 
There is still a question mark for me on how to best deploy the specific environment [described here](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/README.md) for the tutorials suite on try.openbiosim.org 

If you could do some tests and squash the repo before you go on leave I should be able to make any other last minute tweaks in mid-July.

**Comment by lohedges** [comment]
Done. A squashed repo is [here](https://github.com/OpenBioSim/biosimspace_tutorials).
