### ISSUE TITLE
Swap .magnitude() with .value() in funnel metadynamics analysis notebook

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/BioSimSpaceTutorials#21]
Due to an old API update, it's necessary to update `.magnitude()` with `.value()` throughout [this](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/02_funnel_metad/03_bss-fun-metad-analysis.ipynb) notebook

**Comment by lohedges** [comment]
Note that you'll need to wait for [this](https://github.com/OpenBioSim/biosimspace/pull/110) PR to be merged before the notebook will work. Alternatively, you can use that branch locally to get the changes.

**Comment by jmichel80** [comment]
Fixed by #25
