### ISSUE TITLE
Object returned by viewFunnel isn't displayed

### ISSUE THREAD

**Issue by lohedges** [OpenBioSim/BioSimSpaceTutorials#22]
The object returned by `viewFunnel` in [this](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/02_funnel_metad/01_bss-fun-metaD-introduction.ipynb) notebook will need to be displayed in some way, e.g:

```python
# Show everything. (This makes it hard to see the funnel.)
view.system()

# Just show the protein, ligand, and funnel.
view.molecules([0,1,-1])
```

The funnel _is_ displayed in the [second notebook](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/02_funnel_metad/02_bss-fun-metad-tutorial.ipynb). We'll need to decide whether we want to show all molecules, or a reduced view in order to better highlight the funnel.

**Comment by jmichel80** [comment]
fixed by #26
