### ISSUE TITLE
Error executing 04_writing_nodes

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#3]
Running interactively [04_writing_nodes.ipynb](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/01_introduction/04_writing_nodes.ipynb) on Ubuntu Linux with BSS 2023.2.2 , python 3.9.16 triggers a runtime error

![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/b9a30ed9-e2a9-42b5-b7c7-6c2981312976)

I have verified that gmx and sander are in my path

```
(openbiosim) julien@yoko:~/projects/BioSimSpaceTutorials/01_introduction$ echo $AMBERHOME
/home/julien/miniforge3/envs/openbiosim
(openbiosim) julien@yoko:~/projects/BioSimSpaceTutorials/01_introduction$ which gmx
/home/julien/miniforge3/envs/openbiosim/bin.AVX2_256/gmx
(openbiosim) julien@yoko:~/projects/BioSimSpaceTutorials/01_introduction$ which sander
/home/julien/miniforge3/envs/openbiosim/bin/sander
(openbiosim) julien@yoko:~/projects/BioSimSpaceTutorials/01_introduction$ 
```

**Comment by lohedges** [comment]
Are they in the path _inside_ the notebook? I've encountered situations where it doesn't pick up certain environment variables within the notebook session, so have manually set them at the top. If this is the case, then I'll try to work out why it's happening.

**Comment by jmichel80** [comment]
I think the path is correct in the notebook

![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/f3d05a92-8bbb-4ae7-8318-b510969f8f7c)

**Comment by lohedges** [comment]
Oh, I see the issue, you are loading from a mixture of formats, i.e. AMBER coordinates and a GROMACS topology. By default it matches the most suitable engine with the formats that relate to it. In this case nothing is matching. That's strange that it's failing now, since it worked before. Perhaps the wrong filename has been written in the tutorial? In any case, this should be made more robust.

**Comment by jmichel80** [comment]
could you chekc @mb2055  ?

**Comment by mb2055** [comment]
@jmichel80 Can you clarify which files are being loaded here? The files listed as examples in the tutorial (`ala.crd`, `ala.top` and `kigaki.gro`, `kigaki.top`, all of which are found [here](https://github.com/OpenBioSim/BioSimSpaceTutorials/tree/main/01_introduction/inputs)) seem to work without issue on my end, although I suppose this node should work with any matching set of input files.

**Comment by jmichel80** [comment]
ok i must have mixed things up when i downloaded the inputs so I could upload them again to test the dropdown menu in the interactive notebook.
I will close the issue for now and we can log a feature request to make the logic to match inputs to engines more robust.
