### ISSUE TITLE
testing suite on try.openbiosim.org

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#32]
Once the repo has been trimmed we should test that all the notebooks can be executed from [try.openbiosim.org](https://try.openbiosim.org/)

as far as I am aware the tutorials suite require the following dependencies 

BioSimspace release (2023.3.0 or more recent)  
Gromacs (tested with 2023.1) 
AmberTools (tested with 23) 
PLUMED (tested with 2.9.0) -required for Tutorials 2 and 3-
cinnabar (tested with 0.3.0) required for Tutorial 4)

Some notebooks alo use pmemd which we cannot distribute on the server, so some notebooks may have to be updated to  fall back onto using sander.

The tutorials would be available by default in a 'tutorials' folder on the left hand side of the JupyterLab UI 

Is there anything else that I have overlooked?

**Comment by jmichel80** [comment]
Using the BSS and Sire versions provided by default on the notebook server I get a runtime error on try.openbiosim.org at the very end of this notebook  
[01_introduction/03_molecular_dynamics.ipynb](https://try.openbiosim.org/user/jmichel80/lab/tree/BioSimSpaceTutorials/01_introduction/03_molecular_dynamics.ipynb)


![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/0fd9cf0c-203b-42e3-a1cc-0cb471e4507f)

**Comment by lohedges** [comment]
Okay, it's defaulting to the new Sire trajectory backend. We can force it to use `mdtraj` or `mdanalysis`, which can calculate the RMSD correctly.

**Comment by jmichel80** [comment]
One problem with our plan is that we regularly push new updates to biosimspace on the Docker notebook container used for the jupyter server. 

It would be better to have a stable environment to run the tutorials, and update that environment at each major release. Testing that all the tutorials work is another integration test similar to what we plan to run on biosimspace_bigtests. 

What would it take to provide two environments on try.openbiosim ? One that runs devel and allows developers to experiment with the latest functionality, and one that allows users to work with a stable core. 

We could have different entry points ? e.g. try.openbiosim.org/devel  and try.openbiosim.org/stable ?

**Comment by fjclark** [comment]
>as far as I am aware the tutorials suite require the following dependencies

>BioSimspace release (2023.3.0 or more recent)
>Gromacs (tested with 2023.1)
>AmberTools (tested with 23)
>PLUMED (tested with 2.9.0) -required for Tutorials 2 and 3-
>cinnabar (tested with 0.3.0) required for Tutorial 4)

Apologies for not noticing this earlier - the ABFE tutorials also require Alchemlyb for analysis. Also, it's not essential, but the restraint search section mentions the use of the MDRestraintsGenerator restraints search option, which would require [this version](https://github.com/Exscientia/MDRestraintsGenerator) of MDRestraintsGenerator.

Thanks.
