### ISSUE TITLE
02_bss_fun_metad_analysis on try.openbiosim.org

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#35]
Executing this notebook [02_bss-fun-metad-analysis.ipynb](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/test-tryopenbiosim/02_funnel_metad/02_bss-fun-metad-analysis.ipynb) fails with the current runtime error

![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/865978c6-69cd-40e6-949b-abea825c1733)

It looks like the plumed version is not parsed correctly.

**Comment by lohedges** [comment]
This is caused by the changes to the way in which we now parse the plumed version. In the previous approach, the requirement conditional failed when once version 2.10 came out.
