### ISSUE TITLE
Runtime error running 01_bss_fun_metad_setup on try.openbiosim.org

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#36]
Runtime error when trying to run this notebook [01_bss-fun-metad-setup.ipynb](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/test-tryopenbiosim/02_funnel_metad/01_bss-fun-metad-setup.ipynb)  at cell

```
process = BSS.Process.OpenMM(
    equilibrated, protocol, work_dir="fun-metaD-work_dir"
)

process.start()

process.wait()
```

![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/039f1f07-b722-4584-9b02-0812f694743d)

May be related to #35

**Comment by lohedges** [comment]
No, I think this is related to the `work_dir` utility class created in 2023.0.0. Not sure why this wasn't a problem before now.
