### ISSUE TITLE
Missing dataset prevents completion of 03_steered_md/02_trajectory_analysis.ipynb

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#38]
In the notebook [03_steered_md/02_trajectory_analysis.ipynb](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/test-tryopenbiosim/03_steered_md/02_trajectory_analysis.ipynb)

execution of the cell below will fail because the nc file has not been made available. 

```
for i, index in enumerate(frames):
    frame = BSS.Trajectory.getFrame(
        trajectory="/home/adele/Documents/PTP1B/steering.nc",
        topology="/home/adele/Documents/PTP1B/system.prm7",
        index=int(index),
    )
    BSS.IO.saveMolecules(f"{snapshot_dir}/snapshot_{i+1}", frame, "rst7")
```

@AdeleHardie - can you provide steering.nc ? I will add it to the compressed tarball extracted at the beginning of the tutorial.

**Comment by AdeleHardie** [comment]
I no longer have the original file and I can't seem to find where it came from from my original PTP1B work, so I will quickly rerun it and send it over
