### ISSUE TITLE
Error executing Tutorial 2: 01_bss-fun-metaD-introduction

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#4]
Running interactively [01_bss-fun-metaD-introduction](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/02_funnel_metad/01_bss-fun-metaD-introduction.ipynb) on Ubuntu Linux with BSS 2023.2.2 , python 3.9.16 triggers a runtime error

![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/3507889b-39f9-4331-b9c3-ee77192e93ab)

**Comment by lohedges** [comment]
This will be closed via the PR cross-referenced at the link above.
