### ISSUE TITLE
Error executing tutorial Tutorial 2: 02_bss-fun-metad-tutorial.ipynb

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#5]
Running interactively [02_bss-fun-metad-tutorial.ipynb](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/02_funnel_metad/02_bss-fun-metad-tutorial.ipynb) on Ubuntu Linux with BSS 2023.2.2 , python 3.9.16 triggers a runtime error

![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/26cb8ff1-3728-4da9-9c30-d89c70a005a4)

Likely due to updates to the search API

**Comment by lohedges** [comment]
Yep, just meed to call `.molecules()` on the search.

**Comment by mb2055** [comment]
After applying fix #16 along with the "make whole" sire functionality from [here](https://github.com/OpenBioSim/biosimspace/pull/110) another issue arises:
![Screenshot from 2023-06-22 11-28-27](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/53092770/fc69ea67-1cf0-4ddf-b107-0ddb443f8cd1)
This is easily remedied by swapping `["input_files/solvated.pdb"]` with ["input_files/solvated.rst7","input_files/solvated.prm7"]. I will update fix #16 accordingly.

Biosimspace version 2023.3.0 python 3.10.11

**Comment by lohedges** [comment]
Yes, the system will need a space property in order to correctly calculate the funnel coordinates. Presumably any production simulation will used fully prepared files, e.g. the AMBER files you are suggesting. Glad it was an easy fix.

**Comment by lohedges** [comment]
I think the use of a PDB predated the fix needed to handle wrapped molecules, i.e. Dom realised that the funnel coordinates were wrong for certain input files where the ligand was wrapped across the periodic box. At that point we needed to use the space, so probably forgot to update the notebook.

**Comment by jmichel80** [comment]
fixed by #16
