### ISSUE TITLE
Error executing tutorial 3: 01_setup_sMD_AMBER

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#7]
Running interactively [01_setup_sMD_AMBER](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/03_steered_md/01_setup_sMD_AMBER.ipynb) on Ubuntu Linux with BSS 2023.2.2 , python 3.9.16 triggers a runtime error

![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/3e2e6109-70d1-4079-ba80-fcae062b01b8)

My BSS environment uses GROMACS 2023.1, it may be that the default gromacs Protocol settings in BSS are no longer compatible with this GROMACS release ? Pinging @AdeleHardie to comment

**Comment by lohedges** [comment]
Ah, interesting, I'll try locally.

**Comment by jmichel80** [comment]
Fixed by #17

**Comment by lohedges** [comment]
Okay, this is because of a bug in the Exscientia configuration generator that doesn't implement any temperature control for `Steering` protocols, which they don't use. I'll fix this and link to the issue.

**Comment by lohedges** [comment]
Just to say that the fix shouldn't be needed for 2023.3.0, so can be removed if it works when tested.
