### ISSUE TITLE
Runtime error Tutorial 4: alchemical_introduction

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#8]
Running interactively [alchemical_introduction](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/04_fep/01_intro_to_alchemy/alchemical_introduction.ipynb) on Ubuntu Linux with BSS 2023.2.2 , python 3.9.16 triggers a runtime error at the end of the notebook 

![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/052b897f-54c8-478c-96f7-cfefc002cb52)

**Comment by jmichel80** [comment]
This is presumably because the necessary functionality has not been migrated yet from the feature branch here 
https://github.com/michellab/BioSimSpace/blob/feature-analysis/python/BioSimSpace/FreeEnergy/_relative.py#L1486

This could be easily addressed by removing the call to BSS.FreeEnergy.Relative.plot in the tutorial since this is functionality is not essential in the tutorial.

**Comment by lohedges** [comment]
This functionality already exists with `BioSimSpace.Notebook`, so we could use that. I don't want the same (similar) functionality in two places, so we can think about where best to put it when porting the analysis code.

**Comment by mb2055** [comment]
Echoing what @lohedges has said, this is easy to fix by using` fig = BSS.Notebook.plotOverlapMatrix(overlap_matrix_free)`. The plot that this produces has some cosmetic differences to the ones already in the notebook however.

**Comment by lohedges** [comment]
The one from `BioSimSpace.Notebook` should use the plotting approach from the FEP best practice paper. It was originally implemented by @jenkesheen. Happy to adapt it as needed in future.

**Comment by jmichel80** [comment]
@mb2055  you could look at updating the plotting style with BSS.NoteBook.plotOverlapMatrix for consistent with Fig 13 in https://livecomsjournal.org/index.php/livecoms/article/view/v2i1e18378  ? The code to generate the figure is here
https://github.com/alchemistry/alchemical-best-practices/tree/master/paper/figures/fig12_overlap (I think)

**Comment by mb2055** [comment]
BSS.NoteBook.plotOverlapMatrix is already consistent with the best practices paper. The discrepancy is with the overlap `matrices from example_output` such as [this](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/04_fep/01_intro_to_alchemy/example_output/overlap_MBAR_bound.png)

**Comment by jmichel80** [comment]
fixed by #23
